module2-task1
htmlacademy-vue/1280285-pizza-1 pull request #2
Opened 2022-02-25 09:50 UTC by sorokabandit

2022-02-25 10:49 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +  props: ["calcPrice", "pizzaName", "ingObj"],
пропсы нужно описывать подробно - тип + required или default

2022-02-25 10:50 UTC, Djaler commented on src/frontend/src/common/components/RadioButton.vue
> +      v-if="className == 'dough'"
этот базовый компонент не должен знать так много о вариантах его использования. Нужно это как-то более абстрактно передавать в пропсах

2022-02-25 10:51 UTC, Djaler commented on src/frontend/src/common/components/RadioButton.vue
> +    let input = this.$refs.input;
а зачем обращаться к самому элементу? у нас же это значение в пропсах и так есть

2022-02-25 10:52 UTC, Djaler commented on src/frontend/src/common/components/RadioButton.vue
> +      this.$emit("getValueRadio", event.target.value, this.price ? this.price : '', this.multiplier ? this.multiplier : '');
опять таки, значение у нас есть в пропсах, не нужно его доставать из самого элемента с помощью `target.value`

2022-02-25 10:56 UTC, Djaler commented on src/frontend/src/common/components/SelectorItem.vue
> +      count: 0,
хранить в самом компоненте информацию о текущем количестве не нужно. эта информация должна передаваться в пропсах. а наверх нужно событием кидать новое значение количества. Расчёт цены прямо здесь вести не стоит

2022-02-25 11:06 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +          list[i]["size"] = "light";
тут ты мутируешь объекты, находящиеся в исходном массиве, так как `let list = this.list.dough` это просто новая ссылка на тот же массив. А в computed не должно быть никаких мутаций данных

2022-02-25 11:14 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +        classForPizza = "pizza--foundation--big-tomato";
формирование класса стоит перенести ближе к тому месту, где этот класс применяется, передав пропсами нужные для этого данные

2022-02-25 11:14 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +      if (value == "light" || value == "large") {
чтобы не приходилось отталкиваться от того, какое значение прилетает, стоит разделить это на отдельные методы

2022-02-25 11:15 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +    <ItemCounter :calcPrice="calcPrice" :pizzaName="pizzaName" :ingObj="ingObj" @pushToCart="pushToCart"/>
выглядит, как будто тут лишняя прослойка, в которой ничего дополнительного нет

2022-02-25 11:25 UTC, Djaler commented
Расчёт цена идёт неправильно - нужно же учитывать цену всех ингредиентов. А у тебя получается, что каждый раз когда меняем ингредиент - его цена только учитывается

2022-02-25 11:28 UTC, Djaler commented on src/frontend/src/common/components/SelectorItem.vue
> +      draggable="true"
drag-and-drop нужно отключать, когда достигнуто максимальное количество для ингредиента

2022-02-25 11:30 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +      if(event.target.className !== "content__constructor" && !document.querySelector('.content__constructor').contains(event.target)){
не стоит так делать. так получается, что реализация drag-and-drop в каком-то дочернем компоненте зависит от того, что вот тут сделано в самом верху. посмотри как сделано в учебном проекте VueWork - там отдельные компонент AppDrag и AppDrop в себе инкапсулируют всю нужную логику

2022-02-25 12:03 UTC, sorokabandit commented on src/frontend/src/common/components/RadioButton.vue
> +      v-if="className == 'dough'"
Но в задании сказано, что нужно сделать компонент радикнопки, и по этому все дробится так

2022-02-25 12:43 UTC, Djaler commented on src/frontend/src/common/components/RadioButton.vue
> +      v-if="className == 'dough'"
конечно, но компонент радиокнопки не должен в себе содержать такого рода условия. Если у тебя радиокнопка будет использоваться ещё в десяти местах - ты ж не добавишь сюда ещё 10 условий? Нужно просто сделать, чтобы необходимые параметры можно было установить через пропсы

2022-02-27 21:16 UTC, NikolaiKotikov commented
В целом всё работает, кроме кнопки добавления в корзину. Замечания наставника, который делал первичную проверку оставлены по делу, не стоит их игнорировать. По коду вопросов очень много, рекомендую взять консультацию. Дополнительно нужно избавиться от предупреждений в консоли.

2022-02-27 21:18 UTC, NikolaiKotikov requested changes
В целом всё работает, кроме кнопки добавления в корзину. Замечания наставника, который делал первичную проверку оставлены по делу, не стоит их игнорировать. По коду вопросов очень много, рекомендую взять консультацию. Дополнительно нужно избавиться от предупреждений в консоли.

2022-02-27 21:18 UTC, NikolaiKotikov commented on src/frontend/src/common/components/ItemCounter.vue
> +    checkButton() {
Всегда возвращает true, соответственно и кнопка постоянно в состоянии disabled

2022-02-27 21:18 UTC, NikolaiKotikov commented on src/frontend/src/common/components/RadioButton.vue
> +        :checked="checkFirst"
А почему всегда только первый элемент выбирается по умолчанию? Это может быть и любой другой

2022-02-27 21:18 UTC, NikolaiKotikov commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +          list[i]["size"] = "large";
Формировать поле "size" на основании поля "name" не стоит. Это поле может быть переименовано в любой момент, либо вообще приходить из апи. Лучше посмотреть как сделано во VueWork, для чего там файл taskStatuses.js например.

2022-02-27 21:18 UTC, NikolaiKotikov commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +        if (sauce[i].name == "Томатный") {
Опять, мутация данных родительского компонента и очень хрупкая система формирования "value"

2022-02-27 21:18 UTC, NikolaiKotikov commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +        ingredient[i]["class"] = resNew;
Собственно тоже плохая идея. Это здесь названия файлов изображений внятные, в реальности это скорее всего будет просто хэш

2022-02-27 21:18 UTC, NikolaiKotikov commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +              v-if="value >= 3"
Если максимальное число одного ингредиента 3, то это сработает, но если будет 10 например? Лучше придумать что-то более универсальное

2022-02-27 21:18 UTC, NikolaiKotikov commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +        if (list[i].name == "23 см") {
Об этом уже писал

2022-03-07 13:06 UTC, merged